### ISSUE TITLE
Installing to Program Files causes UnauthorizedAccessException when updating

### ISSUE THREAD

**Issue by Stevoisiak** [Assistant/ModAssistant#165]
**Issue:**
If an outdated version of ModAssistant is run from a folder that requires administrator permission, it will crash on startup with `UnauthorizedAccessException`.

**Steps to recreate:**
1. Download an outdated version of ModAssistant. (1.1.8.0)
2. Move ModAssistant to `C:/Program Files/ModAssistant/ModAssistant.exe`.
3. Run ModAssistant.exe.

**Expected result:**
ModAssistant requests administrator rights so it can update itself. If the updater still fails, display an error, but allow the older version of ModAssistant to run.

**Actual result:**
ModAssistant will crash unless it is run as an administrator, or is manually updated to the latest version.

**System:**
- Windows 10 Pro (64-bit)
- ModAssistant 1.1.8.0
- Beat Saber 1.9.1

**Full Error:**
```
An unhandled exception just occurred: System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ModAssistant.Updater.<StartUpdate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModAssistant.Updater.<Run>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModAssistant.App.<>c.<<Init>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModAssistant.App.<Init>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModAssistant.App.<Application_Startup>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Stevoisiak** [comment]
This potentially be the cause of #111.

**Comment by Stevoisiak** [comment]
Thank you for the prompt fix!
