### ISSUE TITLE
COMException when clicking on Mod description text

### ISSUE THREAD

**Issue by Rychard** [Assistant/ModAssistant#188]
On the mod page, clicking on the description of a mod causes an unhandled exception to be thrown, crashing the application.  Clicking on this column is intended to copy the mod's description to the clipboard.

A brief internet search seemed to indicate that this is an issue with WPF and/or DataGrids, but after looking a bit deeper I'm skeptical that there isn't another issue at play.  I initially planned to submit a corresponding pull-request that resolved this issue, but during my testing I found that my changes did not resolve the issue in all scenarios.

I'm not sure what the value-proposition is for copying a mod's description to the clipboard, but an easy solution would be to remove the [`MouseLeftButtonDown` eventhandler from the `TextBlock`](https://github.com/Assistant/ModAssistant/blob/ffba3ca42aa0f58bfd33c84cd20574af93bf02ea/ModAssistant/Pages/Mods.xaml#L95).  (Or at the very least, wrapping it in a `try`/`catch` block)

The exception (and screenshot) is included below.

```text
---------------------------
Exception
---------------------------
An unhandled exception just occurred: System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Clipboard.SetText(String text)
   at ModAssistant.Pages.Mods.CopyText(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```

![image](https://user-images.githubusercontent.com/2145848/83882720-87ed1b80-a710-11ea-88d0-7f7630a888a9.png)

**Comment by megalon** [comment]
I'm unable to reproduce this.
Does it happen when you click on a single mod in particular, or any mod?
Is this still happening with the latest release?

**Comment by Rychard** [comment]
> Does it happen when you click on a single mod in particular, or any mod?

The issue occurs when clicking on the description text of any mod.

> Is this still happening with the latest release?

The issue is still present in the latest release.

I have submitted PR #194 that prevents this issue from occurring.  In the description for that pull request, I've included a more robust explanation of the underlying issue.
